version: "2"
linters:
  enable:
    - gocritic
    - gosec
    - misspell
    - revive
  disable:
    - depguard
    - dupl
    - funlen
    - gocyclo
    - lll
  settings:
    gosec:
      excludes:
        - G115
      severity: medium
    misspell:
      locale: US
    revive:
      severity: warning
      rules:
        - name: exported
          severity: warning
        - name: receiver-naming
        - name: import-shadowing
        - name: var-naming
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
          - gocyclo
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
