run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gosec
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - typecheck
    - misspell
    - revive
    - gocritic
  disable:
    - gocyclo
    - depguard
    - dupl
    - funlen
    - lll

linters-settings:
  misspell:
    locale: US
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
      - name: receiver-naming
      - name: import-shadowing
      - name: var-naming
  gosec:
    severity: medium
    excludes:
      - G115 # integer overflow false positives

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
