name: CI - Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Go tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.x"
          cache: true

      - name: Verify module graph
        run: |
          go mod download
          go mod verify

      - name: Run unit tests
        run: |
          set -euo pipefail
          go test ./... -v -count=1 -race -coverprofile=coverage.out -covermode=atomic -timeout=60s

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage
          path: coverage.out
          if-no-files-found: ignore
